title: Mombasa Ya Imarika
email: hamujent@gmail.com
description: Official campaign site of Senator Faki – Mombasa Ya Imarika
baseurl: "" # leave empty for GitHub Pages
url: "https://yourusername.github.io"
theme: minima
